# This is completely OPTIONAL, you can use it if you want, but it's not necessary
# If you know how to use docker, this is a quick way to create local a mysql database

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    ports:
      - "3306:3306"
    networks:
      - mynetwork

networks:
  mynetwork: